const $=s=>document.querySelector(s);let token=localStorage.getItem("omsai_token"),user=JSON.parse(localStorage.getItem("omsai_user")||"null"),cart=JSON.parse(localStorage.getItem("omsai_cart")||"[]"),mode="login";
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
const money=x=>"₹"+Number(x).toFixed(2);function save(){localStorage.setItem("omsai_cart",JSON.stringify(cart));cartUI()}
function cartUI(){$("#cartCount").textContent=cart.reduce((a,x)=>a+x.quantity,0);$("#cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cartline"><span>${x.name} × ${x.quantity}</span><b>${money(x.unit_price*x.quantity)}</b></div>`).join(""):"<p>Cart is empty.</p>";$("#cartTotal").textContent=cart.length?money(cart.reduce((a,x)=>a+x.unit_price*x.quantity,0)):""}
async function load(){const c=await api("/api/categories");$("#category").innerHTML='<option value="">All categories</option>'+c.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");products();orders()}
async function products(){const d=await api("/api/products?"+new URLSearchParams({q:$("#search").value,category:$("#category").value,sort:$("#sort").value}));$("#products").innerHTML=d.products.map(p=>`<article class="product"><div class="productIcon">💊</div><label>${p.category_name||"Healthcare"}</label><h3>${p.name}</h3><span class="muted">${p.generic_name||""}</span>${p.prescription_required?"<span class='muted'>Prescription required</span>":""}<div class="price">${money(p.price*(1-p.discount/100))}</div><button class="btn" onclick='add(${JSON.stringify(p)})' ${p.stock<1?"disabled":""}>${p.stock<1?"Out of stock":"Add to cart"}</button></article>`).join("")}
window.add=p=>{const x=cart.find(x=>x.productId===p.id);x?x.quantity++:cart.push({productId:p.id,name:p.name,unit_price:Number((p.price*(1-p.discount/100)).toFixed(2)),quantity:1,prescription_required:p.prescription_required});save()};
async function orders(){if(!user){$("#ordersList").innerHTML="<p class='muted'>Sign in to see your orders.</p>";return}const d=await api("/api/orders/mine");$("#ordersList").innerHTML=d.orders.length?d.orders.map(o=>`<div class="order"><b>Order #${o.id}</b><span>${money(o.total)} · ${o.status}</span></div>`).join(""):"<p>No orders yet.</p>"}
function account(){if(user){$("#authForm").classList.add("hidden");$("#logout").classList.remove("hidden");$("#authMsg").textContent="Signed in as "+user.name;if(["admin","pharmacist","staff"].includes(user.role)){$("#admin").classList.remove("hidden");admin()}}else{$("#authForm").classList.remove("hidden");$("#logout").classList.add("hidden")}}
$("#loginTab").onclick=()=>{mode="login";document.querySelectorAll(".reg").forEach(x=>x.classList.add("hidden"))};$("#registerTab").onclick=()=>{mode="register";document.querySelectorAll(".reg").forEach(x=>x.classList.remove("hidden"))};
$("#authForm").onsubmit=async e=>{e.preventDefault();try{const b={email:$("#authEmail").value,password:$("#authPassword").value};if(mode==="register"){b.name=$("#authName").value;b.phone=$("#authPhone").value}const d=await api("/api/auth/"+mode,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});token=d.token;user=d.user;localStorage.setItem("omsai_token",token);localStorage.setItem("omsai_user",JSON.stringify(user));account();orders()}catch(e){$("#authMsg").textContent=e.message}};
$("#logout").onclick=()=>{token=null;user=null;localStorage.removeItem("omsai_token");localStorage.removeItem("omsai_user");account();orders()};
$("#rxForm").onsubmit=async e=>{e.preventDefault();if(!user)return $("#rxMsg").textContent="Please sign in first.";const f=new FormData();f.append("prescription",$("#rxFile").files[0]);try{const d=await api("/api/prescriptions",{method:"POST",body:f});$("#rxMsg").textContent=d.message;e.target.reset()}catch(x){$("#rxMsg").textContent=x.message}};
$("#cartBtn").onclick=()=>{$("#cartDialog").showModal()};$("#checkout").onclick=async()=>{if(!user)return alert("Please sign in first.");if(!cart.length)return;const address=prompt("Address: House, City, State, Pincode");if(!address)return;const a=address.split(",").map(x=>x.trim());try{const d=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart,address:{line1:a[0],city:a[1],state:a[2],pincode:a[3]},paymentMethod:"COD"})});cart=[];save();cartDialog.close();alert("Order #"+d.orderId+" created.");orders()}catch(e){alert(e.message)}};
async function admin(){try{const[s,o,p,r]=await Promise.all([api("/api/admin/summary"),api("/api/admin/orders"),api("/api/admin/products"),api("/api/admin/prescriptions")]);$("#summary").innerHTML=Object.entries(s).map(([k,v])=>`<div class="stat"><label>${k}</label><b>${v}</b></div>`).join("");$("#adminOrders").innerHTML=o.orders.slice(0,10).map(x=>`<div class="adminrow">#${x.id} · ${x.customer} · ${money(x.total)}<select onchange="changeOrder(${x.id},this.value)"><option>${x.status}</option><option>Confirmed</option><option>Preparing</option><option>Ready</option><option>Out for Delivery</option><option>Delivered</option><option>Cancelled</option></select></div>`).join("");$("#adminRx").innerHTML=r.prescriptions.slice(0,10).map(x=>`<div class="adminrow">#${x.id} · ${x.customer} · ${x.status}</div>`).join("");$("#adminProducts").innerHTML=p.products.slice(0,12).map(x=>`<div class="adminrow">${x.name} · stock ${x.stock} · ${money(x.price)}</div>`).join("")}catch(e){console.error(e)}}
window.changeOrder=async(id,status)=>{await api("/api/admin/orders/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});admin()};
$("#search").oninput=products;$("#category").onchange=products;$("#sort").onchange=products;(async()=>{cartUI();await load();account()})();